// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ngram_generator
std::vector<std::map<std::string, int> > ngram_generator(std::vector<std::string> documents, unsigned int n, char delim);
RcppExport SEXP Narrative_ngram_generator(SEXP documentsSEXP, SEXP nSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type documents(documentsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< char >::type delim(delimSEXP);
    __result = Rcpp::wrap(ngram_generator(documents, n, delim));
    return __result;
END_RCPP
}
