# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ngram_generator <- function(sentence, n) {
    .Call('Narrative_ngram_generator', PACKAGE = 'Narrative', sentence, n)
}

tdm_creator <- function(ngrams) {
    .Call('Narrative_tdm_creator', PACKAGE = 'Narrative', ngrams)
}

tdm_generator <- function(documents, n) {
    .Call('Narrative_tdm_generator', PACKAGE = 'Narrative', documents, n)
}

