# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ngram_generator <- function(documents, n, delim) {
    .Call('Narrative_ngram_generator', PACKAGE = 'Narrative', documents, n, delim)
}

